Sprint_14 реализация ветки add-contollers
deicida6/java-shareit pull request #1
Opened 2024-06-25 07:55 UTC by deicida6

2024-06-26 10:13 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody Item item) {
зачем вы создали ItemDto и не используете его?
Используйте это: 
public ItemDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody ItemDto item)

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new AvailableItemException("Не указан статус объекта при создании");
это ValidationException -- вы же валидируете входной параметр.
Я уже оставил коммент, что бы вы использовали ItemDto, поставьте там аннотацию @NotNull над available и эта проверка вам будет не нужна

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userId == null) {
смотрите коммент ниже

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemStorage.getById(itemId) != null) {
```
 {
   Item item = itemStorage.getById(itemId);
   if (item == null) {
      log.error("Объект с таким Id {} не найден", itemId);
      throw new NotFoundException("Объект с таким Id " + itemId + " не найден");
   }
   return itemStorage.getById(itemId);
}
```

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    public Collection<Item> getAll(Long userId) {
getAllByUserId

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        Collection<Item> itemsFiltred = new ArrayList<>();
перепишите через стримы
```
return itemMap.values().stream()
   .filter(it -> it.getOwner().equals(userId))
   .collect(Collectors.toList());
```

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
создайте UserDto и используйте его

2024-06-26 10:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private final UserStorage userDto;
смотрите комменты в ItemServiceImpl

2024-06-26 12:38 UTC, deicida6 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userId == null) {
в смысле про использование itemDto вместо item?

2024-06-26 12:41 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userId == null) {
Про NotNull

2024-06-26 12:41 UTC, deicida6 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userId == null) {
если я использую такой вариант в контроллере    
@PostMapping
    public ItemDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody ItemDto itemDto) {
        return ItemMapper.toItemDto(itemService.create(userId,ItemMapper.fromItemDto(itemDto,userId)));
    }

получится что я принимаю формат ItemDto и возвращаю того же формат но на сервис уходит просто item

2024-06-26 12:42 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (userId == null) {
Можно и так

2024-06-26 12:57 UTC, deicida6 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
а UserDto так понимаю по полям ничем не будет отличаться от User? не увидел уточнения в задании

2024-06-26 13:00 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
По идее они отличаючабтся, в dto мы скрываем некоторые поля, которые юзеру знать не надо

2024-06-26 13:01 UTC, deicida6 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
учитывая что их всего два, то видимо это будет мыло

2024-06-26 13:28 UTC, deicida6 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
все равно не понимаю чем они могут сейчас отличатся, т.к. в тестах постмане при создании user он проверяет все поля и получается нет смысла там возвращать UserDto

2024-06-26 13:32 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
Хорошо, тогда удалите, давайте без них, не забудьте удалить ItemDto

2024-06-26 13:36 UTC, deicida6 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
я оставил оба и ItemDto и UserDto раз это требуется, в itemDto описано что мы не показываем поле owner пользователю, userDto просто ничем не отличается от User просто сделана логика что показываем userDto вместо User

2024-06-26 13:37 UTC, deicida6 commented
отправил на ревью

2024-06-27 11:59 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-06-28 08:14 UTC, merged